### PR TITLE
Initialize API Call

### PR DESCRIPTION
**Pull request by ZaneCodeJourney**
## Description:
This pull request integrates API call functionality into the `MemberTable` component, allowing it to fetch member data from the backend and display it dynamically. The existing hardcoded sample data is preserved as a fallback option in case the API call fails. This implementation is critical for ensuring that the frontend remains functional with real-time data from the backend, improving the overall reliability of the application.

### Key Changes:
1. **`apiService.js`**:
   - Initialized the API service with Axios for making requests to the backend.
   - Configured the `API_BASE_URL` to connect with the appropriate backend endpoint.
   
2. **`MemberTable.jsx`**:
   - Added Axios API call to fetch member data from the backend.
   - Incorporated a fallback mechanism using the hardcoded data if the API call fails.
   - Introduced loading state to improve user experience during data fetching.
   
### Changes in Files:
- **frontend-management/src/api/apiService.js**:
  - Added API service setup using Axios for user management.
  - Modified the `API_BASE_URL` configuration.

- **frontend-management/src/components/MemberTable.jsx**:
  - Refactored the component to fetch data from the backend via API.
  - Added fallback data for reliability when the API is unavailable.
  - Introduced loading state to provide visual feedback to users.

### Future Work:
- Implement error handling for more robust user feedback in case the API call fails.
- Integrate additional data endpoints for other functionalities like adding, editing, and deleting users.

## Testing:
- Verified that the component correctly fetches data from the backend and displays it in the table.
- Tested fallback data handling by intentionally failing the API call to ensure that the table continues to function with hardcoded data.

### Related Issues:
Closes # [Issue number related to API integration].

## Additional Information:
[GitHub Community Guidelines](https://github.com/Chiaraliz/CITS5206_Project)

### CODE REVIEW

**Comment by markzhhang** [comment]
Nice work on adding the API call with fallback data and loading state! This will greatly improve reliability and user experience

**Comment by kjiang001** [comment]
Not working the url is not correct,pls change to like: /api/members

**Comment by FrogCai66** [comment]
"Get" and "Post" for new members are done, do you need api like generate count of active members?

**Comment by SexyZoe** [comment]
I'm having problems with the code change, I'm trying to fix it, so if you have problems using it, talk to me

**Pull request merged**
